// Copies the runtime pieces of three.js, IBM Plex and Phosphor icons into public/vendor
// so the deployed site has no CDN dependency (it also works offline at a talk).
import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const nm = join(here, "node_modules");
const pub = join(here, "..", "site", "public");
const vendor = join(pub, "vendor");

function copy(from, to) {
  const src = join(nm, from);
  if (!existsSync(src)) throw new Error(`missing ${src}`);
  mkdirSync(dirname(join(vendor, to)), { recursive: true });
  cpSync(src, join(vendor, to));
}

// three.js r186 ships no minified build: bundle three + OrbitControls into one ES module.
mkdirSync(join(vendor, "three"), { recursive: true });
await build({
  stdin: {
    contents:
      'export * from "three";\nexport { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";\n',
    resolveDir: here,
    loader: "js",
  },
  bundle: true,
  minify: true,
  format: "esm",
  target: "es2020",
  legalComments: "eof",
  outfile: join(vendor, "three", "three.min.js"),
});
copy("three/LICENSE", "three/LICENSE");

// IBM Plex Sans / Mono, latin + cyrillic subsets, with the unicode ranges Fontsource publishes.
const faces = [];
const fonts = [
  ["ibm-plex-sans", "IBM Plex Sans", [400, 500, 600]],
  ["ibm-plex-mono", "IBM Plex Mono", [400, 500]],
];
for (const [pkg, family, weights] of fonts) {
  copy(`@fontsource/${pkg}/LICENSE`, `fonts/${pkg}-LICENSE`);
  for (const weight of weights) {
    const css = readFileSync(join(nm, `@fontsource/${pkg}/${weight}.css`), "utf8");
    for (const subset of ["latin", "cyrillic"]) {
      const block = css.split(`/* ${pkg}-${subset}-${weight}-normal */`)[1] ?? "";
      const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
      if (!range) throw new Error(`no unicode-range for ${pkg} ${subset} ${weight}`);
      const file = `${pkg}-${subset}-${weight}-normal.woff2`;
      copy(`@fontsource/${pkg}/files/${file}`, `fonts/${file}`);
      faces.push(
        `@font-face{font-family:"${family}";font-style:normal;font-weight:${weight};font-display:swap;` +
          `src:url("./${file}") format("woff2");unicode-range:${range};}`
      );
    }
  }
}
writeFileSync(join(vendor, "fonts", "fonts.css"), faces.join("\n") + "\n");

// Phosphor icons (regular weight), inlined as strings so they inherit currentColor.
const icons = [
  "caret-left", "caret-right", "play", "pause", "info", "translate", "github-logo", "x",
  "arrows-out", "arrows-in", "arrow-counter-clockwise", "cube", "stack", "lock-simple",
  "flask", "check", "warning", "sliders-horizontal", "cursor-click",
];
const lines = ["// Generated by tools/vendor.mjs from @phosphor-icons/core (MIT). Do not edit.", "export const ICONS = {"];
for (const name of icons) {
  const svg = readFileSync(join(nm, `@phosphor-icons/core/assets/regular/${name}.svg`), "utf8")
    .replace(/<svg /, '<svg aria-hidden="true" focusable="false" ')
    .replace(/\s+/g, " ")
    .trim();
  lines.push(`  "${name}": ${JSON.stringify(svg)},`);
}
lines.push("};", "");
copy("@phosphor-icons/core/LICENSE", "icons-LICENSE");
writeFileSync(join(pub, "js", "icons.js"), lines.join("\n"));

// Favicon: the Phosphor brain glyph on a dark rounded tile, readable on light and dark tab bars.
const brain = readFileSync(join(nm, "@phosphor-icons/core/assets/regular/brain.svg"), "utf8");
const glyph = /<path[^>]*\/>/.exec(brain)[0];
writeFileSync(
  join(pub, "favicon.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" rx="56" fill="#0e1116"/>` +
    `<g transform="translate(36 36) scale(0.72)" fill="#eef2f6">${glyph}</g></svg>\n`,
);
console.log("vendored three.js, fonts:", faces.length, "faces, icons:", icons.length);
